//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolWebsite.Resources.Navbar {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SchoolWebsite.Resources.Navbar.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lycée Ibn Batouta.
        /// </summary>
        public static string brand_heading {
            get {
                return ResourceManager.GetString("brand.heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AKLIM.
        /// </summary>
        public static string brand_small {
            get {
                return ResourceManager.GetString("brand.small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S&apos;identifier.
        /// </summary>
        public static string button_identification {
            get {
                return ResourceManager.GetString("button.identification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Langue.
        /// </summary>
        public static string button_language {
            get {
                return ResourceManager.GetString("button.language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Évenements.
        /// </summary>
        public static string list_events {
            get {
                return ResourceManager.GetString("list.events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historique.
        /// </summary>
        public static string list_historic {
            get {
                return ResourceManager.GetString("list.historic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceuil.
        /// </summary>
        public static string list_home {
            get {
                return ResourceManager.GetString("list.home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club Informatique.
        /// </summary>
        public static string list_informaticsClub {
            get {
                return ResourceManager.GetString("list.informaticsClub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reglement.
        /// </summary>
        public static string list_reglement {
            get {
                return ResourceManager.GetString("list.reglement", resourceCulture);
            }
        }
    }
}
