//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolWebsite.Resources.InformaticsClub {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SchoolWebsite.Resources.InformaticsClub.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les élèves apprendront la programmation web (html, css, javascript) à travers la création d’un simple site web du lycée, des simples projets, et des petits jeux..
        /// </summary>
        public static string card1_text {
            get {
                return ResourceManager.GetString("card1.text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qu’apprendront les élèves ?.
        /// </summary>
        public static string card1_title {
            get {
                return ResourceManager.GetString("card1.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tous les élèves qui veulent apprendre à programmer ! Nous commençons par les bases absolues, et après, les élèves peuvent passer a la création de projets plus avancés..
        /// </summary>
        public static string card2_text {
            get {
                return ResourceManager.GetString("card2.text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to À qui s’adresse ce club ?.
        /// </summary>
        public static string card2_title {
            get {
                return ResourceManager.GetString("card2.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C’est un club pédagogique créé dans le but d’apprendre aux élèves les bases de la programmation informatique..
        /// </summary>
        public static string firstCard_text {
            get {
                return ResourceManager.GetString("firstCard.text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qu’est-ce que le club informatique ?.
        /// </summary>
        public static string firstCard_title {
            get {
                return ResourceManager.GetString("firstCard.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remettre à 0.
        /// </summary>
        public static string project1_button {
            get {
                return ResourceManager.GetString("project1.button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clickez sur un button pour augmenter ou diminuer le conteur.
        /// </summary>
        public static string project1_heading {
            get {
                return ResourceManager.GetString("project1.heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /click-counter.
        /// </summary>
        public static string project1_path {
            get {
                return ResourceManager.GetString("project1.path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un simple conteur de click.
        /// </summary>
        public static string project1_title {
            get {
                return ResourceManager.GetString("project1.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de tentatives :.
        /// </summary>
        public static string project2_attempts {
            get {
                return ResourceManager.GetString("project2.attempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vérifier.
        /// </summary>
        public static string project2_button1 {
            get {
                return ResourceManager.GetString("project2.button1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejouer.
        /// </summary>
        public static string project2_button2 {
            get {
                return ResourceManager.GetString("project2.button2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devinez un nombre entre 0 et 10.
        /// </summary>
        public static string project2_heading {
            get {
                return ResourceManager.GetString("project2.heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrer un nombre ici.
        /// </summary>
        public static string project2_input {
            get {
                return ResourceManager.GetString("project2.input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /guess-the-number.
        /// </summary>
        public static string project2_path {
            get {
                return ResourceManager.GetString("project2.path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dommage! Essayez une autre fois.
        /// </summary>
        public static string project2_result1 {
            get {
                return ResourceManager.GetString("project2.result1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bien jouer le nombre est :.
        /// </summary>
        public static string project2_result2 {
            get {
                return ResourceManager.GetString("project2.result2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deviner le nombre.
        /// </summary>
        public static string project2_title {
            get {
                return ResourceManager.GetString("project2.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voir.
        /// </summary>
        public static string projects_button_show {
            get {
                return ResourceManager.GetString("projects.button.show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exemples de projets à réaliser durant les séances.
        /// </summary>
        public static string projectsTitle {
            get {
                return ResourceManager.GetString("projectsTitle", resourceCulture);
            }
        }
    }
}
